from PyQt5 import QtCore, QtGui, QtWidgets
from modules import vaccine_lot

class CreateVaccineLot(object):

    showErrorMessage = None
    showSuccessMessage = None
    manager = vaccine_lot.VaccineLotManager()

    def setupUi(self, createVaccineLot):
        createVaccineLot.setObjectName("createVaccineLot")
        createVaccineLot.resize(400, 681)
        self.inputLotId = QtWidgets.QLineEdit(createVaccineLot)
        self.inputLotId.setGeometry(QtCore.QRect(20, 40, 221, 25))
        self.inputLotId.setObjectName("inputLotId")
        self.inputLotId.setValidator(QtGui.QRegExpValidator(QtCore.QRegExp('\d{1,12}')))
        self.lotId = QtWidgets.QLabel(createVaccineLot)
        self.lotId.setGeometry(QtCore.QRect(20, 20, 121, 17))
        self.lotId.setObjectName("lotId")
        self.manufacturerBox = QtWidgets.QComboBox(createVaccineLot)
        self.manufacturerBox.setGeometry(QtCore.QRect(20, 100, 221, 25))
        self.manufacturerBox.setObjectName("manufacturerBox")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerBox.addItem("")
        self.manufacturerLabel = QtWidgets.QLabel(createVaccineLot)
        self.manufacturerLabel.setGeometry(QtCore.QRect(20, 80, 81, 17))
        self.manufacturerLabel.setObjectName("manufacturerLabel")
        self.vaccineTypeBox = QtWidgets.QComboBox(createVaccineLot)
        self.vaccineTypeBox.setGeometry(QtCore.QRect(20, 160, 221, 25))
        self.vaccineTypeBox.setObjectName("vaccineTypeBox")
        self.vaccineTypeBox.addItem("")
        self.vaccineTypeBox.addItem("")
        self.vaccineTypeBox.addItem("")
        self.vaccineTypeBox.addItem("")
        self.vaccineTypeLabel = QtWidgets.QLabel(createVaccineLot)
        self.vaccineTypeLabel.setGeometry(QtCore.QRect(20, 140, 111, 17))
        self.vaccineTypeLabel.setObjectName("vaccineTypeLabel")
        self.unitsAmountBox = QtWidgets.QSpinBox(createVaccineLot)
        self.unitsAmountBox.setGeometry(QtCore.QRect(20, 220, 111, 26))
        self.unitsAmountBox.setMinimum(1)
        self.unitsAmountBox.setMaximum(999999)
        self.unitsAmountBox.setObjectName("unitsAmountBox")
        self.unitsAmountlabel = QtWidgets.QLabel(createVaccineLot)
        self.unitsAmountlabel.setGeometry(QtCore.QRect(20, 200, 151, 17))
        self.unitsAmountlabel.setObjectName("unitsAmountlabel")
        self.doseLabel = QtWidgets.QLabel(createVaccineLot)
        self.doseLabel.setGeometry(QtCore.QRect(20, 260, 67, 17))
        self.doseLabel.setObjectName("doseLabel")
        self.doseBox = QtWidgets.QSpinBox(createVaccineLot)
        self.doseBox.setGeometry(QtCore.QRect(20, 280, 48, 26))
        self.doseBox.setMinimum(1)
        self.doseBox.setMaximum(9)
        self.doseBox.setObjectName("doseBox")
        self.temperatureLabel = QtWidgets.QLabel(createVaccineLot)
        self.temperatureLabel.setGeometry(QtCore.QRect(20, 320, 231, 17))
        self.temperatureLabel.setObjectName("temperatureLabel")
        self.temperatureBox = QtWidgets.QSpinBox(createVaccineLot)
        self.temperatureBox.setGeometry(QtCore.QRect(20, 340, 101, 26))
        self.temperatureBox.setMinimum(-99)
        self.temperatureBox.setObjectName("temperatureBox")
        self.effectivenessLabel = QtWidgets.QLabel(createVaccineLot)
        self.effectivenessLabel.setGeometry(QtCore.QRect(20, 380, 81, 16))
        self.effectivenessLabel.setObjectName("effectivenessLabel")
        self.effectivenessBox = QtWidgets.QSpinBox(createVaccineLot)
        self.effectivenessBox.setGeometry(QtCore.QRect(20, 400, 61, 26))
        self.effectivenessBox.setMinimum(1)
        self.effectivenessBox.setObjectName("effectivenessBox")
        self.protectionTimeLabel = QtWidgets.QLabel(createVaccineLot)
        self.protectionTimeLabel.setGeometry(QtCore.QRect(20, 440, 151, 17))
        self.protectionTimeLabel.setObjectName("protectionTimeLabel")
        self.protectionTimeBox = QtWidgets.QSpinBox(createVaccineLot)
        self.protectionTimeBox.setGeometry(QtCore.QRect(20, 460, 71, 26))
        self.protectionTimeBox.setMinimum(1)
        self.protectionTimeBox.setMaximum(999)
        self.protectionTimeBox.setObjectName("protectionTimeBox")
        self.dateBox = QtWidgets.QDateEdit(createVaccineLot)
        self.dateBox.setGeometry(QtCore.QRect(20, 520, 110, 26))
        self.dateBox.setObjectName("dateBox")
        self.dateLabel = QtWidgets.QLabel(createVaccineLot)
        self.dateLabel.setGeometry(QtCore.QRect(20, 500, 151, 17))
        self.dateLabel.setObjectName("dateLabel")
        self.imageBox = QtWidgets.QLineEdit(createVaccineLot)
        self.imageBox.setGeometry(QtCore.QRect(20, 580, 251, 25))
        self.imageBox.setObjectName("imageBox")
        self.imageLabel = QtWidgets.QLabel(createVaccineLot)
        self.imageLabel.setGeometry(QtCore.QRect(20, 560, 101, 17))
        self.imageLabel.setObjectName("imageLabel")
        self.createButton = QtWidgets.QPushButton(createVaccineLot)
        self.createButton.setGeometry(QtCore.QRect(150, 630, 89, 25))
        self.createButton.setObjectName("createButton")
        self.createButton.clicked.connect(self.onButtonClicked)

        self.retranslateUi(createVaccineLot)
        QtCore.QMetaObject.connectSlotsByName(createVaccineLot)

    def retranslateUi(self, createVaccineLot):
        _translate = QtCore.QCoreApplication.translate
        createVaccineLot.setWindowTitle(_translate("createVaccineLot", "Crear lote de vacunas"))
        self.lotId.setText(_translate("createVaccineLot", "Número de Lote"))
        self.manufacturerBox.setItemText(0, _translate("createVaccineLot", "Sinovac"))
        self.manufacturerBox.setItemText(1, _translate("createVaccineLot", "Pfizer"))
        self.manufacturerBox.setItemText(2, _translate("createVaccineLot", "Moderna"))
        self.manufacturerBox.setItemText(3, _translate("createVaccineLot", "SputnikV"))
        self.manufacturerBox.setItemText(4, _translate("createVaccineLot", "AstraZeneca"))
        self.manufacturerBox.setItemText(5, _translate("createVaccineLot", "Sinopharm"))
        self.manufacturerBox.setItemText(6, _translate("createVaccineLot", "Covaxim"))
        self.manufacturerLabel.setText(_translate("createVaccineLot", "Fabricante"))
        self.vaccineTypeBox.setItemText(0, _translate("createVaccineLot", "Vector viral"))
        self.vaccineTypeBox.setItemText(1, _translate("createVaccineLot", "ARN/ADN"))
        self.vaccineTypeBox.setItemText(2, _translate("createVaccineLot", "Virus desactivado"))
        self.vaccineTypeBox.setItemText(3, _translate("createVaccineLot", "En base a proteínas"))
        self.vaccineTypeLabel.setText(_translate("createVaccineLot", "Tipo de Vacuna"))
        self.unitsAmountlabel.setText(_translate("createVaccineLot", "Unidades Disponibles"))
        self.doseLabel.setText(_translate("createVaccineLot", "Dosis"))
        self.temperatureLabel.setText(_translate("createVaccineLot", "Temperatura de Almacenamiento"))
        self.effectivenessLabel.setText(_translate("createVaccineLot", "Efectividad"))
        self.protectionTimeLabel.setText(_translate("createVaccineLot", "Tiempo de Protección"))
        self.dateBox.setDisplayFormat(_translate("createVaccineLot", "d/M/yyyy"))
        self.dateLabel.setText(_translate("createVaccineLot", "Fecha de Vencimiento"))
        self.imageLabel.setText(_translate("createVaccineLot", "Foto del lote"))
        self.createButton.setText(_translate("createVaccineLot", "Crear"))

    def onButtonClicked(self):

        if self.inputLotId.text() == "":
            self.showErrorMessage("Ingrese número de lote")
            return

        lotId = int(self.inputLotId.text())
        lot = self.manager.find_lot(lotId)

        if bool(lot):
            self.showErrorMessage("Número de lote ya existe")
            return

        manufacturer = self.manufacturerBox.currentText()
        vaccineType = self.vaccineTypeBox.currentText()
        units = self.unitsAmountBox.value()
        dose = self.doseBox.value()
        temperature = self.temperatureBox.value()
        effectiveness = self.effectivenessBox.value()
        protectionTime = self.protectionTimeBox.value()
        date = int(self.dateBox.dateTime().toPyDateTime().timestamp())
        img = self.imageBox.text()
        res = self.manager.new_lot(vaccine_lot.VaccineLot(lotId, manufacturer, vaccineType, 
                                                          units, dose, temperature, effectiveness, protectionTime, date, img))
        if res:
            self.showSuccessMessage("Lote creado con éxito")
        else:
            self.showErrorMessage("Error creando el lote intente de nuevo")

